version: '3'

services:
  backend:
    build: ./spam-sniffer-backend
    container_name: spam-sniffer-backend
    ports:
      - "5000:5000"
    volumes:
      - ./spam-sniffer-backend:/app
    restart: always

  frontend:
    build: ./spam-sniffer-frontend
    container_name: spam-sniffer-frontend
    ports:
      - "3000:80"
    volumes:
      - ./spam-sniffer-frontend:/app
    restart: always
